name: build to my github

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - name: Build
        run: yarn build

      # - name: CreateTag
      #   run git tag -a
      - name: Deploy
        uses: dongzupeng/blog
        with:
          deploy_key: ${{ secrets.ACTION_TOKEN }}
          publish_dir: docs/.vitepress/dist